CREATE TABLE cliente (
	COD_CLIENTE SERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	LOGIN VARCHAR(10) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	ENDERECO VARCHAR(32) NOT NULL,
	CIDADE VARCHAR(32) NOT NULL,
	BAIRRO VARCHAR(32) NOT NULL,
	ESTADO VARCHAR(32) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
PRIMARY KEY (COD_CLIENTE));

CREATE TABLE estoque (
	id SERIAL NOT NULL,
	COD_LIVRO varchar(50),
	TITULO VARCHAR(30) NOT NULL,
	AUTOR VARCHAR(20) NOT NULL,
	PRECO NUMERIC NOT NULL,
	IMAGEM VARCHAR(80) NOT NULL,
	DESCRICAO VARCHAR(80),
PRIMARY KEY (id));

CREATE TABLE item_pedido (
	COD_ITEM SERIAL NOT NULL,
	QTD int NOT NULL,
	COD_LIVRO BIGINT NOT NULL,
	COD_PEDIDO BIGINT NOT NULL,
	PRIMARY KEY (COD_ITEM));

CREATE TABLE pedido (
	COD_PEDIDO SERIAL NOT NULL,
	DATA_PEDIDO DATE NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	COD_CLIENTE BIGINT NOT NULL,
	PRIMARY KEY (COD_PEDIDO));